### ISSUE TITLE
Mobile - Portrait | List View Issues

### ISSUE THREAD

**Issue by Valenie** [ajency/F-BCircle#11]
1) Published Date is not displayed
![image](https://user-images.githubusercontent.com/19943710/28018058-6797fb4a-6599-11e7-81f2-12c273f084f2.png)

2) The lower section of the list view which shows get details and recent updates is not proper.
![image](https://user-images.githubusercontent.com/19943710/28018101-95e6c134-6599-11e7-804a-a4bdaa25124b.png)

3) Advertisement not displayed
4) There should be clear action for individual filter
5) "Search by" should be "Search By"

![image](https://user-images.githubusercontent.com/19943710/28018395-d6894f6c-659a-11e7-9d0c-25156e817aec.png)

6) the checkboxes are not proper
![screenshot_20170710-182026](https://user-images.githubusercontent.com/19943710/28019088-4aa2c23c-659d-11e7-8bff-498e3d85e9b2.png)

7) send enquiry action is not displayed all the time on scroll
![image](https://user-images.githubusercontent.com/19943710/28019853-02cd2666-65a0-11e7-9f68-7c3a6d811f0e.png)

**Comment by ajajrajguru** [comment]
Less important stuff ignored rest all is fixed

**Comment by Valenie** [comment]
@ajajrajguru 

Advertisement and published date should be there.

**Comment by ajajrajguru** [comment]
Added
