### ISSUE TITLE
Mobile - Safari | List view issues

### ISSUE THREAD

**Issue by Valenie** [ajency/F-BCircle#12]
1) The list view is broken
2) Send enquiry action is not present
3) When the user clicks on the menu item (3 lines). not able to go back to the list view
4) Check boxes are not proper
![img_5467](https://user-images.githubusercontent.com/19943710/28019590-16d3e5f6-659f-11e7-8433-1b22cbd15764.PNG)
![img_5468](https://user-images.githubusercontent.com/19943710/28019589-16d20448-659f-11e7-8225-ee2fb0464d57.PNG)
![img_5469](https://user-images.githubusercontent.com/19943710/28019588-16d0bb92-659f-11e7-808b-bd10759b1095.PNG)

**Comment by ajajrajguru** [comment]
Fixed
