### ISSUE TITLE
Safari - Mobile | Single view of listing issues

### ISSUE THREAD

**Issue by Valenie** [ajency/F-BCircle#5]
1) Header elements too close to each other
2) The arrows besides the breadcrumb - "Next " moves out 
3) Share is too big
4) "+10" for areas of operation moves out
5) "Show Contact Info" text  alignment - not proper
6) Year of establishment and website should be on separate lines
7) Only one business and one news article is displayed on the screen... there is no indication for the user that the have to scroll to the right to see another.
8) The scroll able menu does not scroll to the similar businesses or articles when the resp sections are reached.
![img_5461](https://user-images.githubusercontent.com/19943710/27944612-b8999bac-6305-11e7-863c-eef83b6d32b3.PNG)
![img_5462](https://user-images.githubusercontent.com/19943710/27944615-b89d257e-6305-11e7-87c4-1b50dac181c5.PNG)
![img_5463](https://user-images.githubusercontent.com/19943710/27944616-b89d9702-6305-11e7-8da8-6f7ea27e321f.PNG)
![img_5464](https://user-images.githubusercontent.com/19943710/27944613-b89c11c0-6305-11e7-99d7-a8ccb633bc65.PNG)
![img_5465](https://user-images.githubusercontent.com/19943710/27944614-b89ce28a-6305-11e7-8e3e-ae9ece585903.PNG)

**Comment by ajajrajguru** [comment]
Fixed
